/**
 * Local DDragon asset URL helpers.
 *
 * These resolve to self-hosted, pre-optimized WebP images under /assets/ddragon/.
 * Assets are generated by `scripts/optimize-ddragon.ts` and committed to the repo.
 *
 * Fallback: if a local asset is missing (e.g. new champion before the action runs),
 * the shared icon components fall back to the raw DDragon/CommunityDragon URL.
 */

import { getRankEmblemUrl as getCDragonRankUrl } from "@/lib/rank-utils";
import {
  getChampionIconUrl as getDDragonChampionUrl,
  getKeystoneIconUrl,
  getKeystoneIdByName,
} from "@/lib/riot-api";

// ─── Champion icon name normalization (must match optimize-ddragon.ts) ───────

const CHAMPION_NAME_FIXES: Record<string, string> = {
  FiddleSticks: "Fiddlesticks",
};

function normalizeChampionName(name: string): string {
  return CHAMPION_NAME_FIXES[name] || name;
}

// ─── Local asset URL builders ───────────────────────────────────────────────

export function getLocalChampionIconUrl(championName: string, size: number): string {
  return `/assets/ddragon/champion/${size}/${normalizeChampionName(championName)}.png`;
}

export function getLocalItemIconUrl(itemId: number, size: number): string {
  return `/assets/ddragon/item/${size}/${itemId}.png`;
}

export function getLocalRuneIconUrl(keystoneId: number, size: number): string {
  return `/assets/ddragon/rune/${size}/${keystoneId}.png`;
}

/**
 * Get local rune icon URL by keystone name (reverse-lookup).
 * Returns null if the name is unknown.
 */
export function getLocalRuneIconUrlByName(keystoneName: string, size: number): string | null {
  const id = getKeystoneIdByName(keystoneName);
  if (id === null) return null;
  return getLocalRuneIconUrl(id, size);
}

export function getLocalRankEmblemUrl(tier: string, size: number): string {
  return `/assets/ddragon/rank-emblem/${size}/${tier.toLowerCase()}.png`;
}

// ─── Fallback URL builders (remote CDN) ─────────────────────────────────────

export function getFallbackChampionIconUrl(version: string, championName: string): string {
  return getDDragonChampionUrl(version, championName);
}

export function getFallbackItemIconUrl(version: string, itemId: number): string {
  return `https://ddragon.leagueoflegends.com/cdn/${version}/img/item/${itemId}.png`;
}

export function getFallbackRuneIconUrl(keystoneId: number): string | null {
  return getKeystoneIconUrl(keystoneId);
}

export function getFallbackRankEmblemUrl(tier: string): string {
  return getCDragonRankUrl(tier);
}
